EMPLOYEE_STATUSES = [
    ('active', 'Active'),
    ('probation', 'Probation'),
    ('on_leave', 'On Leave'),
    ('sabbatical', 'Sabbatical'),
    ('terminated', 'Terminated'),
    ('resigned', 'Resigned'),
    ('retired', 'Retired'),
    ('contract_ended', 'Contract Ended'),
    ('intern', 'Intern'),
    ('consultant', 'Consultant'),
    ('furloughed', 'Furloughed'),
    ('pending', 'Pending Onboarding'),
    ('rejected', 'Rejected Application'),
    ('transferred', 'Transferred'),
    ('deceased', 'Deceased'),
    ('under_review', 'Under Review'),
    ('awaiting_clearance', 'Awaiting Clearance'),
    ('contractor_active', 'Contractor (Active)'),
    ('contractor_inactive', 'Contractor (Inactive)'),
    ('freelancer', 'Freelancer'),
    ('trainee', 'Trainee'),
    ('seconded', 'Seconded'),
    ('layoff_pending', 'Layoff Pending'),
    ('rehired', 'Rehired'),
    ('offboarded', 'Offboarded'),
    ('medical_leave', 'Medical Leave'),
    ('maternity_leave', 'Maternity Leave'),
    ('paternity_leave', 'Paternity Leave'),
    ('unpaid_leave', 'Unpaid Leave'),
    ('study_leave', 'Study Leave'),
    ('suspended', 'Suspended'),
    ('preboarding', 'Preboarding'),
    ('other', 'Other'),
]

CONTRACT_TYPES = [
    ('full_time', 'Full-Time'),
    ('part_time', 'Part-Time'),
    ('contract', 'Contract'),
    ('temporary', 'Temporary'),
    ('internship', 'Internship'),
    ('freelance', 'Freelance'),
    ('remote', 'Remote'),
    ('on_demand', 'On-Demand'),
    ('consultant', 'Consultant'),
    ('seasonal', 'Seasonal'),
    ('probation', 'Probationary'),
    ('apprenticeship', 'Apprenticeship'),
    ('commission_based', 'Commission-Based'),
    ('project_based', 'Project-Based'),
    ('zero_hour', 'Zero-Hour Contract'),
    ('permanent', 'Permanent'),
    ('fixed_term', 'Fixed-Term'),
    ('gig', 'Gig'),
    ('volunteer', 'Volunteer'),
    ('unionized', 'Unionized'),
    ('remote_contract', 'Remote Contract'),
    ('trainee', 'Trainee'),
    ('temp_to_perm', 'Temp-to-Perm'),
    ('subcontract', 'Subcontract'),
    ('labor_union', 'Labor Union'),
    ('freelance_contract', 'Freelance Contract'),
    ('consultancy', 'Consultancy'),
    ('outsourced', 'Outsourced'),
    ('job_sharing', 'Job Sharing'),
    ('contract_for_services', 'Contract for Services'),
    ('work_from_home', 'Work From Home'),
    ('service_agreement', 'Service Agreement'),
    ('independent_contractor', 'Independent Contractor'),
    ('retainer', 'Retainer'),
    ('commission_only', 'Commission Only'),
    ('crowdsource', 'Crowdsourced'),
    ('non_exclusive', 'Non-Exclusive'),
    ('exclusive', 'Exclusive'),
    ('other', 'Other'),
]

ROLES = [
    ('employee', 'Employee'),
    ('employer', 'Employer')
]

THEMES = [
    ('dark', 'Dark'),
    ('light', 'Light')
]
