COMPANY_TYPES = [
    ('client', 'Client'),
    ('contractor', 'Contractor'),
    ('internal', 'Internal'),
    ('vendor', 'Vendor'),
    ('partner', 'Partner'),
    ('subsidiary', 'Subsidiary'),
    ('affiliate', 'Affiliate'),
    ('government', 'Government'),
    ('non_profit', 'Non-Profit'),
    ('distributor', 'Distributor'),
    ('reseller', 'Reseller'),
    ('outsourcer', 'Outsourcer'),
    ('freelancer', 'Freelancer'),
    ('consultant', 'Consultant'),
    ('investor', 'Investor'),
    ('prospect', 'Prospect'),
    ('auditor', 'Auditor'),
    ('competitor', 'Competitor'),
    ('other', 'Other'),
]

EMPLOYEE_STATUSES = [
    ('active', 'Active'),
    ('probation', 'Probation'),
    ('on_leave', 'On Leave'),
    ('sabbatical', 'Sabbatical'),
    ('terminated', 'Terminated'),
    ('resigned', 'Resigned'),
    ('retired', 'Retired'),
    ('contract_ended', 'Contract Ended'),
    ('intern', 'Intern'),
    ('consultant', 'Consultant'),
    ('furloughed', 'Furloughed'),
    ('pending', 'Pending Onboarding'),
    ('rejected', 'Rejected Application'),
    ('transferred', 'Transferred'),
    ('deceased', 'Deceased'),
    ('under_review', 'Under Review'),
    ('awaiting_clearance', 'Awaiting Clearance'),
    ('contractor_active', 'Contractor (Active)'),
    ('contractor_inactive', 'Contractor (Inactive)'),
    ('freelancer', 'Freelancer'),
    ('trainee', 'Trainee'),
    ('seconded', 'Seconded'),
    ('layoff_pending', 'Layoff Pending'),
    ('rehired', 'Rehired'),
    ('offboarded', 'Offboarded'),
    ('medical_leave', 'Medical Leave'),
    ('maternity_leave', 'Maternity Leave'),
    ('paternity_leave', 'Paternity Leave'),
    ('unpaid_leave', 'Unpaid Leave'),
    ('study_leave', 'Study Leave'),
    ('suspended', 'Suspended'),
    ('preboarding', 'Preboarding'),
    ('other', 'Other'),
]

CONTRACT_TYPES = [
    ('full_time', 'Full-Time'),
    ('part_time', 'Part-Time'),
    ('contract', 'Contract'),
    ('temporary', 'Temporary'),
    ('internship', 'Internship'),
    ('freelance', 'Freelance'),
    ('remote', 'Remote'),
    ('on_demand', 'On-Demand'),
    ('consultant', 'Consultant'),
    ('seasonal', 'Seasonal'),
    ('probation', 'Probationary'),
    ('apprenticeship', 'Apprenticeship'),
    ('commission_based', 'Commission-Based'),
    ('project_based', 'Project-Based'),
    ('zero_hour', 'Zero-Hour Contract'),
    ('permanent', 'Permanent'),
    ('fixed_term', 'Fixed-Term'),
    ('gig', 'Gig'),
    ('volunteer', 'Volunteer'),
    ('unionized', 'Unionized'),
    ('remote_contract', 'Remote Contract'),
    ('trainee', 'Trainee'),
    ('temp_to_perm', 'Temp-to-Perm'),
    ('subcontract', 'Subcontract'),
    ('labor_union', 'Labor Union'),
    ('freelance_contract', 'Freelance Contract'),
    ('consultancy', 'Consultancy'),
    ('outsourced', 'Outsourced'),
    ('job_sharing', 'Job Sharing'),
    ('contract_for_services', 'Contract for Services'),
    ('work_from_home', 'Work From Home'),
    ('service_agreement', 'Service Agreement'),
    ('independent_contractor', 'Independent Contractor'),
    ('retainer', 'Retainer'),
    ('commission_only', 'Commission Only'),
    ('crowdsource', 'Crowdsourced'),
    ('non_exclusive', 'Non-Exclusive'),
    ('exclusive', 'Exclusive'),
    ('other', 'Other'),
]

DOCUMENT_TYPES = [
    ('passport', 'Passport'),
    ('id_card', 'ID Card'),
    ('driver_license', 'Driver’s License'),
    ('birth_certificate', 'Birth Certificate'),
    ('residence_permit', 'Residence Permit'),
    ('national_id', 'National ID'),
    ('social_security_card', 'Social Security Card'),
    ('visa', 'Visa Document'),
    ('employment_contract', 'Employment Contract'),
    ('offer_letter', 'Offer Letter'),
    ('promotion_letter', 'Promotion Letter'),
    ('termination_letter', 'Termination Letter'),
    ('salary_slip', 'Salary Slip'),
    ('work_permit', 'Work Permit'),
    ('payslip', 'Payslip'),
    ('background_check', 'Background Check Report'),
    ('nda', 'Non-Disclosure Agreement'),
    ('reference_letter', 'Reference Letter'),
    ('warning_letter', 'Warning Letter'),
    ('cv', 'Curriculum Vitae (CV)'),
    ('resume', 'Resume'),
    ('diploma', 'Diploma'),
    ('degree', 'Degree Certificate'),
    ('transcript', 'Transcript'),
    ('certification', 'Professional Certification'),
    ('training_certificate', 'Training Certificate'),
    ('language_certificate', 'Language Proficiency Certificate'),
    ('tax_form', 'Tax Form'),
    ('bank_statement', 'Bank Statement'),
    ('insurance', 'Insurance Document'),
    ('contract', 'Legal Contract'),
    ('invoice', 'Invoice'),
    ('proof_of_address', 'Proof of Address'),
    ('credit_report', 'Credit Report'),
    ('court_document', 'Court Document'),
    ('affidavit', 'Affidavit'),
    ('consent_form', 'Consent Form'),
    ('medical_record', 'Medical Record'),
    ('vaccination_record', 'Vaccination Record'),
    ('emergency_contact', 'Emergency Contact Info'),
    ('photo', 'Photograph'),
    ('employee_handbook', 'Employee Handbook'),
    ('timesheet', 'Timesheet'),
    ('travel_document', 'Travel Document'),
    ('project_file', 'Project File'),
    ('other', 'Other'),
]
