COMPANY_TYPES = [
    ('client', 'Client'),
    ('contractor', 'Contractor'),
    ('internal', 'Internal'),
    ('vendor', 'Vendor'),
    ('partner', 'Partner'),
    ('subsidiary', 'Subsidiary'),
    ('affiliate', 'Affiliate'),
    ('government', 'Government'),
    ('non_profit', 'Non-Profit'),
    ('distributor', 'Distributor'),
    ('reseller', 'Reseller'),
    ('outsourcer', 'Outsourcer'),
    ('freelancer', 'Freelancer'),
    ('consultant', 'Consultant'),
    ('investor', 'Investor'),
    ('prospect', 'Prospect'),
    ('auditor', 'Auditor'),
    ('competitor', 'Competitor'),
    ('other', 'Other'),
]

DOCUMENT_TYPES = [
    ('passport', 'Passport'),
    ('id_card', 'ID Card'),
    ('driver_license', 'Driver’s License'),
    ('birth_certificate', 'Birth Certificate'),
    ('residence_permit', 'Residence Permit'),
    ('national_id', 'National ID'),
    ('social_security_card', 'Social Security Card'),
    ('visa', 'Visa Document'),
    ('employment_contract', 'Employment Contract'),
    ('offer_letter', 'Offer Letter'),
    ('promotion_letter', 'Promotion Letter'),
    ('termination_letter', 'Termination Letter'),
    ('salary_slip', 'Salary Slip'),
    ('work_permit', 'Work Permit'),
    ('payslip', 'Payslip'),
    ('background_check', 'Background Check Report'),
    ('nda', 'Non-Disclosure Agreement'),
    ('reference_letter', 'Reference Letter'),
    ('warning_letter', 'Warning Letter'),
    ('cv', 'Curriculum Vitae (CV)'),
    ('resume', 'Resume'),
    ('diploma', 'Diploma'),
    ('degree', 'Degree Certificate'),
    ('transcript', 'Transcript'),
    ('certification', 'Professional Certification'),
    ('training_certificate', 'Training Certificate'),
    ('language_certificate', 'Language Proficiency Certificate'),
    ('tax_form', 'Tax Form'),
    ('bank_statement', 'Bank Statement'),
    ('insurance', 'Insurance Document'),
    ('contract', 'Legal Contract'),
    ('invoice', 'Invoice'),
    ('proof_of_address', 'Proof of Address'),
    ('credit_report', 'Credit Report'),
    ('court_document', 'Court Document'),
    ('affidavit', 'Affidavit'),
    ('consent_form', 'Consent Form'),
    ('medical_record', 'Medical Record'),
    ('vaccination_record', 'Vaccination Record'),
    ('emergency_contact', 'Emergency Contact Info'),
    ('photo', 'Photograph'),
    ('employee_handbook', 'Employee Handbook'),
    ('timesheet', 'Timesheet'),
    ('travel_document', 'Travel Document'),
    ('project_file', 'Project File'),
    ('other', 'Other'),
]

HOLIDAY_TYPES = [
    ('holiday', 'Holiday'),
    ('bank_holiday', 'Bank Holiday'),
    ('sick_day', 'Sick Day'),
]
